//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace LindegaardProductions.Web.Models.ModelsBuilder
{
	/// <summary>Frontpage</summary>
	[PublishedModel("frontpage")]
	public partial class Frontpage : PublishedContentModel, IHeader, INavigation, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const string ModelTypeAlias = "frontpage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Frontpage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Frontpage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Gallery: Selected images that you want visitors to see.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("gallery")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> Gallery => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("gallery");

		///<summary>
		/// Page Icon: Add an icon from fontawesome For exampel: {i class="fas fa-music"}{/i}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("pageIcon")]
		public string PageIcon => this.Value<string>("pageIcon");

		///<summary>
		/// Sound files: For visitors to hear some samples of music.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("soundFiles")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> SoundFiles => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("soundFiles");

		///<summary>
		/// Sub Heading: Placed beneath the title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("subHeading")]
		public string SubHeading => global::LindegaardProductions.Web.Models.ModelsBuilder.Header.GetSubHeading(this);

		///<summary>
		/// Title: Title is shown in hero area. And is the main title for the page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("title")]
		public string Title => global::LindegaardProductions.Web.Models.ModelsBuilder.Header.GetTitle(this);

		///<summary>
		/// Video: Select a video for the header. It will play in a loop in the background.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("video")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Video => global::LindegaardProductions.Web.Models.ModelsBuilder.Header.GetVideo(this);

		///<summary>
		/// Hide from menu: Hide page from the menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide => global::LindegaardProductions.Web.Models.ModelsBuilder.Navigation.GetUmbracoNaviHide(this);

		///<summary>
		/// Meta Description: A short description of the content of the page. Will be shown on google and facebook etc. As well on cards on the website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::LindegaardProductions.Web.Models.ModelsBuilder.SEO.GetMetaDescription(this);

		///<summary>
		/// Meta Image: The image of the page, will be seen on cards, and when sharing the page on social media, or searched on google
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("metaImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent MetaImage => global::LindegaardProductions.Web.Models.ModelsBuilder.SEO.GetMetaImage(this);

		///<summary>
		/// MetaTitle: Title that will be seen on google or facebook etc. when sharing the page. And as the title in the tab in your browser.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle => global::LindegaardProductions.Web.Models.ModelsBuilder.SEO.GetMetaTitle(this);
	}
}
